# Generated by Django 4.2.3 on 2023-07-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Sarlavha')),
                ('task', models.TextField(verbose_name='Yozishni boshlang')),
            ],
        ),
    ]
